name: Build and Release Electron App

on:
    push:
        branches:
            - main

jobs:
    build-and-release:
        name: Build and Release
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Generate Tag
              id: tag
              run: |
                  # Generate a unique version tag based on the date and time
                  VERSION=$(date +"%Y%m%d%H%M%S")
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git tag -a "v${VERSION}" -m "Automated release tag v${VERSION}"
                  git push origin "v${VERSION}"
                  echo "TAG=v${VERSION}" >> $GITHUB_ENV

            - name: Build Electron App
              run: npm run build
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload to GitHub Releases
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ env.TAG }} 
                  files: |
                      dist/*.dmg
                      dist/*.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
