name: Build and Release Electron App

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Electron Apps for macOS and Windows
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install Dependencies
              run: npm install

            - name: Build App
              run: |
                  npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Upload Release Artifacts
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dist/*.dmg
                      dist/*.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
